# Generated by Django 4.1.5 on 2023-01-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d')),
                ('status', models.CharField(choices=[('active', 'Актиный'), ('deactive', 'Не актиный')], default='active', max_length=100)),
                ('show_in_home', models.CharField(choices=[('active', 'Актиный'), ('deactive', 'Не актиный')], default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10000)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Актиный'), ('deactive', 'Не актиный')], default='active', max_length=100)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
